baseURL: "https://www.jiongwu.org" 
title: Jiong Wu
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: CV
          url: cv.pdf
          weight: 1

params:
    description: "I am a PhD candidate in economics at University of Virginia."
    author: Jiong Wu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jiong Wu
          subtitle: "Welcome! I am a PhD candidate in economics at University of Virginia. I am on the 2024-25 job market and available for interviews. My research focuses on the intersections of international trade, macroeconomics, labor economics, and urban economics, with a strong emphasis on understanding the interplay between trade shocks, labor markets, and regional dynamics. I employ both structural modeling and empirical analysis, leveraging quantitative tools to explore the effects of globalization on labor market outcomes and regional economic disparities. I adopt machine learning algorithms to solve high-dimensional optimization problems."
          imageUrl: "picture.jpg"
          imageWidth: 308
          imageHeight: 364
          imageTitle: Jiong Wu
          buttons:
            - name: Research
              url: research/
            - name: CV
              url: cv.pdf
    socialIcons:
        - name: Email
          url: mailto:jw3tz@virginia.edu
        - name: LinkedIn
          url: https://www.linkedin.com/in/jiong-wu-uva

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jiong Wu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
