baseURL: "https://www.jiongwu.org" 
title: Jiong Wu
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: CV
          url: cv.pdf
          weight: 1

params:
    description: "I am a PhD candidate in economics at University of Virginia."
    author: Jiong Wu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jiong Wu
          subtitle: "Welcome! I am a PhD candidate in economics at University of Virginia. I am on the 2024-25 job market and will be available for interviews. My research interest centers on international trade and macroeconomics. My job market paper looks into the unemployment effects of China shock on the US regional labor markets. I use machine learning algorithms to solve high-dimensional optimization problems."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jiong Wu
          buttons:
            - name: Research
              url: research/
            - name: CV
              url: cv.pdf
    socialIcons:
        - name: Email
          url: mailto:jw3tz@virginia.edu
        - name: LinkedIn
          url: https://www.linkedin.com/in/jiong-wu-uva
    mainSections:
      - title: "Job Market Paper"
        content: |
          [**Labor Market Responses to Trade: Job Creation and Destruction Across Space and Sectors**](jmp.pdf) <br>

          <details>
            <summary> Abstract </summary>
            In an era dominated by globalization and international trade, the impact of trade shocks on employment has become a pressing concern for policymakers and the public. This paper examines the impact of the China trade shock on U.S. local labor markets, focusing on unemployment and its key drivers: job finding and job separation rates. Using a shift-share design, I find that regions exposed to the shock experience significant and persistent unemployment increases due to lower job finding and higher job separation rates. To explain these results, I develop a dynamic multi-sector, multi-region labor matching model with endogenous job creation and destruction. The calibrated model confirms that trade shocks raise unemployment, decrease employment, and increase welfare inequality across most U.S. states. The China trade shock raises the U.S. unemployment rate by 0.18% and accounts for 87% of the decline in the manufacturing employment share of working-age population from 2000 to 2007, while boosting overall productivity by 0.16% and improving welfare by 0.04%. The model shows that the Hosios condition alone cannot achieve constrained efficiency due to migration frictions and nontradable goods. A redistributive corporate tax policy subsidizing manufacturing could improve welfare, reduce unemployment, and restore pre-shock manufacturing employment levels.
            
          </details>
          <b> Interactive Map: </b>
          <iframe src="/maps/interactive_map.html" width="100%" height="600" style="border:none;"></iframe>

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jiong Wu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
